
server:
  port: 8084

spring:
  application:
    name: API-GATEWAY

  cloud:
    gateway:
      routes:
        - id: USER-SERVICE
          uri: lb://USER-SERVICE
          predicates:
            - Path=/users/**
        - id: RATING-SERVICE
          uri: lb://RATING-SERVICE
          predicates:
            - Path=/ratings/**
        - id: HOTEL-SERVICE
          uri: lb://HOTEL-SERVICE
          predicates:
            - Path=/hotels/**
eureka:
  instance:
    prefer-ip-address: true        # Register the instance using its IP instead of hostname.
  client:
    fetch-registry: true           # Enable fetching the registry from Eureka server.
    register-with-eureka: true     # Enable registration of this service with Eureka.
    service-url:
      defaultZone: http://localhost:8761/eureka  # Eureka server URL

