server:
  port: 8083

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/microservices_rating_service
    username: root
    password: Ashu@123
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  application:
    name: RATING-SERVICE

eureka:
  instance:
    prefer-ip-address: true        # Register the instance using its IP instead of hostname.
  client:
    fetch-registry: true           # Enable fetching the registry from Eureka server.
    register-with-eureka: true     # Enable registration of this service with Eureka.
    service-url:
      defaultZone: http://localhost:8761/eureka  # Eureka server URL
