spring:
  data:
    mongodb:
      uri:
      database:

#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/microservices_rating_service
#    username: root
#    password: Ashu@123
#    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: 8083

